- Imap.php
to get only one message by given ID
> getMessage function

- Imap.php
- outlook.php
- view.php
Hello!
I do any updates in your class, please see the commits.
> General updates

- Imap.php
Hi, just a proposal - provide option to immediately subscribe to a new folder
> added option to subscribe when adding a new folder

- README.md
- example-composer.php
- example-direct.php
My recent PR got accepted. Forgot to tell devs all about it! Silly me!
> Whats the point in adding something if it wont get used!

- ImapClient/ImapClient.php
- README.md
Yay me i did it add in 1 commit this time...
> Added quota and quota_root functions and added documentation for th

- ImapClient/ImapClient.php
I've changed in $emails = array();
> $emails =[] doesn't work to me

- ImapClient/ImapClient.php
- README.md
- composer.json
Just let contributors know that if they want their name in  the credits, they need to do it them selves
> A tid-bit of info for developers and new options for un read emails

- .gitignore
- ImapClient/ImapClient.php
> Fixing errors and cleaning code!

- ImapClient/ImapClient.php
> #55. Added PSR-2 formatting :)

- ImapClient/ImapClient.php
> Fix Embedded images not showing up

- README.md
- example-composer.php
- example-direct.php
- tests/example-connect.php
Change readme, example-composer and example-connect files.
> Check for advanced connect options

- ImapClient/ImapClient.php
> Fix issue #63

- README.md
- docs/guide-en/AdvancedConnecting.md
- docs/guide-en/Error.md
- docs/guide-en/Install.md
- docs/guide-en/Methods.md
- docs/guide-en/README.md
- docs/guide-en/Usage.md
> Fix docs errors

- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE
- ImapClient/ImapClient.php
- docs/guide-en/Error.md
- docs/guide-en/Methods.md
- docs/guide-en/Usage.md
Fixed the issue and pull request templates
Added getEmail and getEmailSafe
Add doc for getEmail and getEmailSafe
> Fixed the issue and pull request templates and more

- ImapClient/ImapClient.php
- docs/guide-en/Usage.md
> Fix doc error

- composer.json
> I think it should be better ;)

- composer.json
For composer install minimum-stability - dev
> Add in composer.json minimum-stability - dev

- ImapClient/ImapClient.php
- ImapClient/ImapClientException.php
- ImapClient/ImapConnect.php
- LICENSE
- README.md
Yes
Updated copy right years
N/A
N/A
N/A
[*] Added your name to the credits
[*] Add a update name below:
Happy Merry New Year
> Happy merry new year

- ImapClient/ImapClient.php
- ImapClient/ImapClientException.php
- ImapClient/ImapConnect.php
- composer.json
Fixed composer loading. Namespacing was wrong.
> Fixed namespacing discrepancies for autoloading.

- ImapClient/ImapClient.php
There are '-' starting lines which break all code and can't be used
[*] Added your name to the credits
[*] Add a update name below:
Remove breaking code characters
> Remove breaking code characters

- .gitignore
- composer.json
Yes
Small adjustments on composer.json
Installing this library on an environment without IMAP PHP extension.
Not applicable.
No.
No.
Rubens Takiguti Ribeiro
> Composer adjustments

- ImapClient/ImapClient.php
> fix issue #94

- .gitignore
- ImapClient/ImapClient.php
- ImapClient/ImapClientException.php
- ImapClient/IncomingMessage.php
- ImapClient/TypeAttachments.php
- ImapClient/TypeBody.php
- TODO
- composer.json
- docs/guide-en/Usage.md
Sorry, I'm not sure about the correctness of the merger. Check your recent edits.
Some improvements in getMessage
> Some improvements

- ImapClient/ImapClient.php
- docs/guide-en/IncomingMessage.md
- docs/guide-en/Install.md
- docs/guide-en/Usage.md
Added an additional description in the code. Fixed the name of the property of the incoming message.
> Added an additional description and some fixes

- docs/guide-en/Methods.md
getMessage function parameter is only $id
$withbody = true does not exist.
> getMessage($id)

- ImapClient/ImapClient.php
- ImapClient/IncomingMessage.php
- ImapClient/TypeAttachments.php
- docs/guide-en/Usage.md
fixed
$obj->structure->encoding in IncomingMessage
and fixed
$imap->getUnreadMessages(false);
$imap->setUnseenMessage('104,103');
add
$imap->getBriefInfoMessages()
$imap->getSection(104, 1)
> Important. Fixed encoding error for body message.

- ImapClient/ImapClient.php
- ImapClient/IncomingMessage.php
- ImapClient/TypeAttachments.php
- ImapClient/TypeBody.php
- docs/guide-en/Usage.md
> Add descriptions and docs

- ImapClient/AdapterForOutgoingMessage.php
- docs/guide-en/AdapterForOutgoingMessage.md
- docs/guide-en/Methods.md
- docs/guide-en/Usage.md
How use adapter for outgoing message.
> How use adapter for outgoing message.

- ImapClient/TypeBody.php
> Fixes #120

- ImapClient/IncomingMessage.php
- ImapClient/IncomingMessageAttachment.php
- docs/guide-en/IncomingMessage.md
Yeah, I reforked
- Refactored the getAttachment and getBody methods in IncomingMessage class
- Added getAttachments method to IncomingMessage class which exposes API methods for the user
None
This time, yes!
Done a right good job
No
Could do with writing some tests for this, here's what I'm using for now:
```php
<?php
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
require_once "php-imap-client/ImapClient/ImapClientException.php";
require_once "php-imap-client/ImapClient/ImapConnect.php";
require_once "php-imap-client/ImapClient/ImapClient.php";
require_once "php-imap-client/ImapClient/IncomingMessage.php";
require_once "php-imap-client/ImapClient/IncomingMessageAttachment.php";
require_once "php-imap-client/ImapClient/TypeAttachments.php";
require_once …
```
> Let's try this again

- ImapClient/ImapClient.php
Yes
Add russian folders names
Yes
> Add russian folders

- composer.json
Add Composer check for `imap` extension.
> Require imap extension

- ImapClient/IncomingMessage.php
- lib is not working with this last changes and logging errors
- pls fix
> Last guy fucked up

- docs/connecting.html
- docs/contributing.html
- docs/errordb.html
- docs/examples.html
- docs/gettingstarted.html
- docs/incomingmessage.html
- docs/index.html
- docs/installing.html
- docs/methods.html
- docs/outgoing.html
- docs/usage.html
> fix misprint ("Intaling" > "Installing")

- docs/guide/methods.md
Yes
Just fix url to english version (from German)
> Fix url to to php.net to English version

- ImapClient/ImapClient.php
Yes.
Fix return values according to phpdoc.
Not fixed bug. Fixed code analysis warnings.
Yes.
Yes.
No.
No.
> fix return values according to phpdoc

- ImapClient/IncomingMessage.php
- ImapClient/SubtypeBody.php
yes
Unicode and decoding of messages
if the source string is not ISO-8859-1, benerated strings by convertToUtf8 function are unreadable
yes
dont know
yes
no
> fix incoming message charset

- ImapClient/ImapClient.php
- ImapClient/IncomingMessage.php
Added work-around for Issue-185 where to array was not filled with all recipients.
I found this solution on: http://php.net/manual/en/function.imap-headerinfo.php#98809
After testing it does do the trick and the To array is filled properly with this change.
> Added work-around for Issue-185.

- ImapClient/IncomingMessage.php
Added support for utf-8 encoding and quoted printable characters on plaintext emails
Yes
Added support for utf-8 and quoted printable characters
Wrong characters read
Yes
Yes
No
[X] Added your name to the credits
> Added support for utf-8 and quoted printable

- ImapClient/IncomingMessage.php
yes
Added support for emails encoded in base64
When an email was read the plain text wasn't decoded from base64 ($objNew->plain)
yes
yes
no
[X] Added your name to the credits
> Added support for base64 encoded mail

- ImapClient/IncomingMessage.php
Yes
no features
Issue #225 
Yes
Not needed
Yes
No
> - fixed issue #225 from giuspe

- ImapClient/IncomingMessage.php
- ImapClient/IncomingMessageAttachment.php
Yes
- Issue #187 
- An issue with iconv that produces an error "iconv(): Detected an incomplete multibyte character in input string" in case if the input text uses mixed encoding.
Yes
Not needed
No
No
> Fix for #187; fix for a problem with iconv and mixed encoding
